const { getDefaultConfig } = require('expo/metro-config');
const fs = require('fs');
const path = require('path');

const SONGS_DIR = path.join(__dirname, 'assets/songs');
const MANIFEST_JSON = path.join(__dirname, 'src/data/songs_manifest.json');
const AUDIO_TS = path.join(__dirname, 'src/data/songs_audio.ts');

// Bootstrap songs_manifest.json as empty array on a fresh clone.
// Actual data is populated by: npm run songs
if (!fs.existsSync(MANIFEST_JSON)) {
  fs.mkdirSync(path.dirname(MANIFEST_JSON), { recursive: true });
  fs.writeFileSync(MANIFEST_JSON, '[]', 'utf8');
  console.log('[metro] songs_manifest.json created (empty — run npm run songs to populate)');
}

// Always regenerate songs_audio.ts to stay in sync with assets/songs/.
{
  if (!fs.existsSync(SONGS_DIR)) fs.mkdirSync(SONGS_DIR, { recursive: true });

  const required = ['audio.mp3', 'song_info.json', 'translation_final.json'];
  const folders = fs.readdirSync(SONGS_DIR)
    .filter((name) => {
      const dir = path.join(SONGS_DIR, name);
      return (
        fs.statSync(dir).isDirectory() &&
        required.every((f) => fs.existsSync(path.join(dir, f)))
      );
    })
    .sort();

  const entries = folders
    .map((folder) => `  ${folder}: require('../../assets/songs/${folder}/audio.mp3'),`)
    .join('\n');

  const content =
    `// AUTO-GENERATED by metro.config.js — do not edit.\n` +
    `export const AUDIO: Record<string, number> = {\n${entries}${entries ? '\n' : ''}};\n`;

  fs.mkdirSync(path.dirname(AUDIO_TS), { recursive: true });
  fs.writeFileSync(AUDIO_TS, content, 'utf8');

  console.log(`[metro] songs_audio.ts generated with ${folders.length} song(s)`);
}

const config = getDefaultConfig(__dirname);
module.exports = config;
